// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU9ZhfnSO7mqa8POsA9iw1LPe-WZ7ia-8',
    appId: '1:119739198721:web:23eb53f39dbdc4f6b0bf00',
    messagingSenderId: '119739198721',
    projectId: 'flutter-the-wall-bd335',
    authDomain: 'flutter-the-wall-bd335.firebaseapp.com',
    storageBucket: 'flutter-the-wall-bd335.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDIi1pNGfnbQHAJU2cRacuhh3KVvWDmuA',
    appId: '1:119739198721:android:c05505750799aceeb0bf00',
    messagingSenderId: '119739198721',
    projectId: 'flutter-the-wall-bd335',
    storageBucket: 'flutter-the-wall-bd335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6fcb5LXuKMEZUJXGLuJ-HOxWTtVa1nfw',
    appId: '1:119739198721:ios:6b8e867fdc2b27f7b0bf00',
    messagingSenderId: '119739198721',
    projectId: 'flutter-the-wall-bd335',
    storageBucket: 'flutter-the-wall-bd335.appspot.com',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6fcb5LXuKMEZUJXGLuJ-HOxWTtVa1nfw',
    appId: '1:119739198721:ios:ec1639d643666c7bb0bf00',
    messagingSenderId: '119739198721',
    projectId: 'flutter-the-wall-bd335',
    storageBucket: 'flutter-the-wall-bd335.appspot.com',
    iosBundleId: 'com.example.theWall.RunnerTests',
  );
}
