// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7L9uSLwTByboE-RXG7OtLtKKSVFIsoY4',
    appId: '1:56130669447:web:7e90bcff9703aa9bafa122',
    messagingSenderId: '56130669447',
    projectId: 'capstone-project-2fbbc',
    authDomain: 'capstone-project-2fbbc.firebaseapp.com',
    storageBucket: 'capstone-project-2fbbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Lm0J7VUoitTl4KZ37CpI9e_oNLRT_gA',
    appId: '1:56130669447:ios:bd186c61974eb0d9afa122',
    messagingSenderId: '56130669447',
    projectId: 'capstone-project-2fbbc',
    storageBucket: 'capstone-project-2fbbc.appspot.com',
    iosClientId:
        '56130669447-u91qs71vlj1diqaunvadqbjm82u4rn33.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymBuddyApp',
  );
}
