name: gym_buddy_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_spinbox: ^0.12.0

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_ui_auth: ^1.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
